# Generated by Django 2.1.5 on 2019-02-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='severity',
            field=models.CharField(choices=[(0, 'low'), (1, 'medium'), (2, 'high')], default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
